#:tombi toml-version = "v1.0.0"

[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/capsula-cli"]

[workspace.package]
version = "0.15.0"
edition = "2024"
rust-version = "1.95"
readme = "README.md"
repository = "https://github.com/ut-issl/capsula"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1"
askama = "0.16"
askama_web = { version = "0.16", features = ["axum-0.8"] }
axum = { version = "0.8", features = ["multipart"] }
capsula-api-types = { path = "crates/capsula-api-types", version = "0.15.0" }
capsula-capture-command = { path = "crates/capsula-capture-command", version = "0.15.0" }
capsula-capture-cwd = { path = "crates/capsula-capture-cwd", version = "0.15.0" }
capsula-capture-env = { path = "crates/capsula-capture-env", version = "0.15.0" }
capsula-capture-file = { path = "crates/capsula-capture-file", version = "0.15.0" }
capsula-capture-git-repo = { path = "crates/capsula-capture-git-repo", version = "0.15.0" }
capsula-capture-json = { path = "crates/capsula-capture-json", version = "0.15.0" }
capsula-capture-machine = { path = "crates/capsula-capture-machine", version = "0.15.0" }
capsula-capture-toml = { path = "crates/capsula-capture-toml", version = "0.15.0" }
capsula-capture-yaml = { path = "crates/capsula-capture-yaml", version = "0.15.0" }
capsula-client = { path = "crates/capsula-client", version = "0.15.0" }
capsula-config = { path = "crates/capsula-config", version = "0.15.0" }
capsula-core = { path = "crates/capsula-core", version = "0.15.0" }
capsula-notify-slack = { path = "crates/capsula-notify-slack", version = "0.15.0" }
capsula-orchestration = { path = "crates/capsula-orchestration", version = "0.15.0" }
capsula-registry = { path = "crates/capsula-registry", version = "0.15.0" }
capsula-tui = { path = "crates/capsula-tui", version = "0.15.0" }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive", "env"] }
crossterm = "0.29"
dotenvy = "0.15.7"
git2 = "0.21"
glob = "0.3"
mime_guess = "2"
names = { version = "0.14", default-features = false }
percent-encoding = "2.3.2"
ratatui = "0.30"
reqwest = { version = "0.13", features = ["blocking", "json", "multipart"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
shlex = "2"
sql-json-path = "0.2"
sqlx = { version = "0.9", features = [
  "chrono",
  "postgres",
  "runtime-tokio",
  "tls-rustls"
] }
sysinfo = "0.39"
tempfile = "3"
testcontainers-modules = { version = "0.15", features = ["postgres"] }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
toml = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ulid = { version = "3", features = ["serde"] }
wiremock = "0.6"
yaml_serde = "0.10"

[workspace.lints.clippy]
all = "warn"
allow_attributes = { level = "warn", priority = 1 }
allow_attributes_without_reason = { level = "warn", priority = 1 }
cargo = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
correctness = { level = "deny", priority = -1 }  # deny-by-default
dbg_macro = { level = "warn", priority = 1 }
decimal_literal_representation = { level = "warn", priority = 1 }
derive_partial_eq_without_eq = { level = "allow", priority = 1 }  # We implement `Eq` only when necessary
else_if_without_else = { level = "warn", priority = 1 }
expect_used = { level = "warn", priority = 1 }
indexing_slicing = { level = "allow", priority = 1 }  # TODO: change to "warn" later
missing_errors_doc = { level = "allow", priority = 1 }  # TODO: change to "warn" later
missing_panics_doc = { level = "allow", priority = 1 }  # TODO: change to "warn" later
multiple_crate_versions = { level = "allow", priority = 1 }  # There is nothing we can do about this
nursery = { level = "warn", priority = -1 }
panic = { level = "warn", priority = 1 }
pedantic = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
print_stderr = { level = "warn", priority = 1 }
print_stdout = { level = "warn", priority = 1 }
style = { level = "warn", priority = -1 }  # warn-by-default
suspicious = { level = "warn", priority = -1 }
todo = { level = "warn", priority = 1 }
undocumented_unsafe_blocks = { level = "warn", priority = 1 }
unimplemented = { level = "warn", priority = 1 }
unwrap_used = { level = "warn", priority = 1 }

[workspace.lints.rust]
# missing-docs = "warn"
unsafe-code = "warn"
