[package]
name = "capsula-cli"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }

clap = { version = "4.5.47", features = ["derive"] }
