name: Bump version
run-name: Bump version to v${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version, without the `v` prefix (e.g. `1.2.3`)'
        required: true

env:
  PYTHON_VERSION: "3.11"

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Bump version
      run: |
        poetry version ${{ github.event.inputs.version }}

    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "Bump version to ${{ github.event.inputs.version }}"
        new_branch: "bump-version/v${{ github.event.inputs.version }}"

  create-pull-request:
    name: Create pull request if on main
    runs-on: ubuntu-latest
    needs: bump-version
    if: github.ref == 'refs/heads/main'
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v3

    - name: Create pull request if on main
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr create --repo ${{ github.repository }} --base main --head "bump-version/v${{ github.event.inputs.version }}" --title "Bump version to v${{ github.event.inputs.version }}" --body "Bump version to v${{ github.event.inputs.version }}"
