name: Bump version
run-name: Bump version to v${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g. `1.2.3`)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tbump

    - name: Bump version
      run: tbump --non-interactive --only-patch ${{ github.event.inputs.version }}

    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "Bump version to ${{ github.event.inputs.version }}"
        new_branch: "bump-version/v${{ github.event.inputs.version }}"

    - name: Create pull request if on main
      if: github.ref == 'refs/heads/main'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr create --fill --repo ${{ github.repository }} --base main
