name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-docs.yml"
      - "capsula/**"
      - "docs/**"
      - "scripts/gen_pages.py"
      - "mkdocs.yml"
      - "pyproject.toml"
      - "README.md"


env:
  PYTHON_VERSION: "3.12"
  UV_VERSION: "0.5.x"
  UV_FROZEN: "1"
  UV_NO_SYNC: "1"

concurrency:
  group: "deploy-docs"
  cancel-in-progress: true

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install the project
        run: uv sync --no-dev --group docs

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch --prune --unshallow

      - name: Update the docs
        run: uv run -- mike deploy --push dev
