name: Bump version, commit, create release and publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      # with:
        # python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tbump poetry

    - name: Bump version
      run: tbump --non-interactive --only-patch ${{ github.event.inputs.version }}

    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "Bump version to ${{ github.event.inputs.version }}"

    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create v${{ github.event.inputs.version }} --generate-notes

    - name: Publish to PyPI
      run: |
        poetry publish --build
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
